// <auto-generated />
using System;
using Day09Lab.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Day09Lab.Migrations
{
    [DbContext(typeof(QlbanHangContext))]
    partial class QlbanHangContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Day09Lab.Models.CtHoaDon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("DonGiaMua")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("HoaDonId")
                        .HasColumnType("int")
                        .HasColumnName("HoaDonID");

                    b.Property<int?>("SanPhamId")
                        .HasColumnType("int")
                        .HasColumnName("SanPhamID");

                    b.Property<int?>("SoLuongMua")
                        .HasColumnType("int");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("PK__CT_HOA_D__3214EC2748397BD1");

                    b.HasIndex("HoaDonId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("CT_HOA_DON", (string)null);
                });

            modelBuilder.Entity("Day09Lab.Models.HoaDon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTenKhachHang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaHoaDon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayHoaDon")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayNhan")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("TongTriGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("PK__HOA_DON__3214EC2701F86DE7");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("HOA_DON", (string)null);
                });

            modelBuilder.Entity("Day09Lab.Models.KhachHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTenKhachHang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaKhachHang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgayDangKy")
                        .HasColumnType("datetime");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("PK__KHACH_HA__3214EC2789061B61");

                    b.ToTable("KHACH_HANG", (string)null);
                });

            modelBuilder.Entity("Day09Lab.Models.LoaiSanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaLoai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenLoai")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("PK__LOAI_SAN__3214EC27D4DCD1FB");

                    b.ToTable("LOAI_SAN_PHAM", (string)null);
                });

            modelBuilder.Entity("Day09Lab.Models.QuanTri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MatKhau")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TaiKhoan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("PK__QUAN_TRI__3214EC27D876CA03");

                    b.ToTable("QUAN_TRI", (string)null);
                });

            modelBuilder.Entity("Day09Lab.Models.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("MaLoai")
                        .HasColumnType("int");

                    b.Property<string>("MaSanPham")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("PK__SAN_PHAM__3214EC2712E4685B");

                    b.HasIndex("MaLoai");

                    b.ToTable("SAN_PHAM", (string)null);
                });

            modelBuilder.Entity("Day09Lab.Models.CtHoaDon", b =>
                {
                    b.HasOne("Day09Lab.Models.HoaDon", "HoaDon")
                        .WithMany("CtHoaDons")
                        .HasForeignKey("HoaDonId")
                        .HasConstraintName("FK__CT_HOA_DO__HoaDo__5535A963");

                    b.HasOne("Day09Lab.Models.SanPham", "SanPham")
                        .WithMany("CtHoaDons")
                        .HasForeignKey("SanPhamId")
                        .HasConstraintName("FK__CT_HOA_DO__SanPh__5629CD9C");

                    b.Navigation("HoaDon");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("Day09Lab.Models.HoaDon", b =>
                {
                    b.HasOne("Day09Lab.Models.KhachHang", "MaKhachHangNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKhachHang")
                        .HasConstraintName("FK__HOA_DON__MaKhach__52593CB8");

                    b.Navigation("MaKhachHangNavigation");
                });

            modelBuilder.Entity("Day09Lab.Models.SanPham", b =>
                {
                    b.HasOne("Day09Lab.Models.LoaiSanPham", "MaLoaiNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaLoai")
                        .HasConstraintName("FK__SAN_PHAM__MaLoai__4F7CD00D");

                    b.Navigation("MaLoaiNavigation");
                });

            modelBuilder.Entity("Day09Lab.Models.HoaDon", b =>
                {
                    b.Navigation("CtHoaDons");
                });

            modelBuilder.Entity("Day09Lab.Models.KhachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("Day09Lab.Models.LoaiSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("Day09Lab.Models.SanPham", b =>
                {
                    b.Navigation("CtHoaDons");
                });
#pragma warning restore 612, 618
        }
    }
}
